# Generated by Django 5.2.15 on 2026-06-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("photographer", "Photographer"),
                            ("partnership", "Partnership"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("organization_website", models.URLField(blank=True, null=True)),
                ("portfolio_link", models.URLField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
