# Generated by Django 5.2.15 on 2026-06-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("what_she_is_doing", models.TextField()),
                ("submitted_by_name", models.CharField(max_length=255)),
                ("submitted_by_email", models.EmailField(max_length=254)),
                ("reviewed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
