# Generated by Django 5.2.15 on 2026-08-22 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('woman_name', models.CharField(max_length=255)),
                ('quote', models.TextField()),
                ('summary', models.TextField()),
                ('story_content', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('read_time', models.PositiveIntegerField(default=5)),
                ('featured', models.BooleanField(default=False)),
                ('hero_story', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('published_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.category')),
            ],
        ),
    ]
