# Generated by Django 5.2.15 on 2026-08-27 20:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_storysection_storysectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='author_image'),
        ),
        migrations.AddField(
            model_name='story',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='story',
            name='role_or_subtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
